### ISSUE TITLE
第七章 application资源的yaml怎么写

### ISSUE THREAD

**Issue by tanlay** [daniel-hutao/Advanced-Kubernetes-Operator#5]
书籍150页。 代码逻辑写完，执行make install后，可以查询到crd，但是查询不到application资源，应该是需要编写application资源的yaml文件，然后创建。yaml不知道咋写，各位大佬支援下呢，谢谢！
1. 查询到applications的crd
```shell
$ kubectl get crd applications.apps.tanlay.com 
NAME                           CREATED AT
applications.apps.tanlay.com   2023-01-29T12:57:45
```
2. 查询applications资源
```shell
$ kubectl get application
No resources found in default namespace.
```
3. 编写application资源的yaml文件
```yaml
apiVersion: apps.tanlay.com/v1
kind: Application
metadata:
  name: application-sample
spec:
  # TODO(user): Add fields here
  deployment:
    ...
  service:
    ...
```

**Comment by tanlay** [comment]
已经搞定了。
1. 编写application的yaml
```yaml
apiVersion: apps.tanlay.com/v1
kind: Application
metadata:
  name: nginx-sample
  namespace: default
  labels:
    app: nginx
spec:
  deployment:
    replicas: 3
    selector:
      matchLabels:
        app: nginx
    template:
      metadata:
        labels:
          app: nginx
      spec:
        containers:
          - image: nginx
            name: nginx
            ports:
              - containerPort: 80
  service:
    type: NodePort
    ports:
      - port: 80
        targetPort: 80
        nodePort: 30880
```
2. 查看app
```shell
$ kubectl get app
NAME           AGE
nginx-sample   10m
```
